"""added title

Revision ID: 08a76b4f5d81
Revises: 09a6448ad958
Create Date: 2025-05-26 01:57:39.594031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a76b4f5d81'
down_revision: Union[str, None] = '09a6448ad958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea_scripts', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea_scripts', 'title')
    # ### end Alembic commands ###
