"""linked idea and tags

Revision ID: 89e922b53999
Revises: 5f82aac0cf33
Create Date: 2025-05-19 04:05:55.692492

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '89e922b53999'
down_revision: Union[str, None] = '5f82aac0cf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
