"""image table

Revision ID: 8eae94ae6532
Revises: 71dcb3112827
Create Date: 2025-05-30 07:08:19.192422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eae94ae6532'
down_revision: Union[str, None] = '71dcb3112827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=255), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_images_id'), 'idea_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_images_id'), table_name='idea_images')
    op.drop_table('idea_images')
    # ### end Alembic commands ###
